### ISSUE TITLE
Please update Store API call

### ISSUE THREAD

**Issue by cprov** [alfonsosanchezbeato/jetson-kernel-snap#1]
The Store API call used to discover the core download URL is using a deprecated service hostname and endpoint, eventually it will stop working:

https://github.com/alfonsosanchezbeato/jetson-kernel-snap/blob/fb0e34a9b68cfa6c46d8e292f37c39d2e26b2b46/src/build.sh#L33

Can you please replace it with:

```
core_url=$(curl -s -H "Snap-Device-Series: 16" "https://api.snapcraft.io/v2/snaps/info/core" \
                   | jq '.["channel-map"] | map(select(.channel.name == "stable" and .channel.architecture == "arm64")) | .[0] | .download.url' -r)
```

**Comment by alfonsosanchezbeato** [comment]
Thanks for the info, changed in https://github.com/alfonsosanchezbeato/jetson-kernel-snap/commit/628fd658a81b62fd1748d688d67a39293c83d022
