### ISSUE TITLE
Xavier kernel needs to be cross compiled

### ISSUE THREAD

**Issue by jimmylomro** [alfonsosanchezbeato/jetson-kernel-snap#3]
The binary `parts/firmware/build/Linux_for_Tegra/bootloader/tegrasign_v2` run from the overrride build of the part `abootimg` is built for amd processors and thus cannot be run from a Jetson Xavier.

**Comment by alfonsosanchezbeato** [comment]
Unfortunately, `tegrasign_v2` is a binary that comes with the L4T driver package, and it comes only for x86, so for the moment there is no solution for this. You will need to build the kernel snap on x86.
