### ISSUE TITLE
Which patches are required for snapd confinement

### ISSUE THREAD

**Issue by om26er** [alfonsosanchezbeato/jetson-kernel-snap#6]
The patch directory contains a whole ton of patches that get applied to the kernel source https://github.com/alfonsosanchezbeato/jetson-kernel-snap/tree/master/src/l4t_32.1.0/patch -- I wanted to know which patches are required for snapd confinement only, we'd want to keep the number of patches to a small set in our project.

**Comment by om26er** [comment]
@alfonsosanchezbeato Your feedback here would be very helpful

**Comment by alfonsosanchezbeato** [comment]
@om26er most patches are apparmor patches for confinement, and of the few that are left the majority are reverts of Android-related commits (yes, nvidia based their kernel on Android 4.9) that were breaking lxd/multipass. So, in fact I would not recommend dropping any patch if you want confinement. Note though that most if not all the patches are upstreamed, so it should not be such a maintenance headache if/when you upgrade to a new kernel.

**Comment by om26er** [comment]
Thanks, I am using all the patches from the above URL and it works for me.
